# Generated by Django 3.2.19 on 2023-05-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_name', models.CharField(max_length=75)),
                ('inquiry_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('inquiry_message', models.TextField()),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
