# Generated by Django 3.2.19 on 2023-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230525_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Promotion', 'Promotion'), ('Sale', 'Sale'), ('News', 'News'), ('Partner Advert', 'Partner Advert'), ('Holiday', 'Holiday'), ('B.T.S', 'B.T.S'), ('Meet the Staff', 'Meet the Staff')], max_length=200, null=True),
        ),
    ]
