# Generated by Django 3.2.19 on 2023-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_date',
            field=models.DateField(),
        ),
    ]
