# Generated by Django 3.2.19 on 2023-05-25 16:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_small_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='detail image'),
        ),
    ]
