# Generated by Django 3.2.19 on 2023-05-16 12:39

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=14, validators=[bookings.models.validate_phone_number])),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=5)),
                ('room_choice', models.CharField(max_length=200)),
                ('comment', models.TextField(default='', max_length=300)),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
