# Generated by Django 3.2.19 on 2023-05-22 22:06

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slot', models.CharField(choices=[('00:00', '00:00'), ('02:00', '02:00'), ('04:00', '04:00'), ('06:00', '06:00'), ('08:00', '08:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00'), ('20:00', '20:00'), ('22:00', '22:00')], max_length=5)),
            ],
            options={
                'ordering': ['game_slot'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200, unique=True)),
                ('room_description', models.TextField()),
                ('blog_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('comment', models.TextField(default='', max_length=300)),
                ('user_id', models.IntegerField(default=0)),
                ('room_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_choice', to='bookings.room')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='bookings.gametime')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
