# Generated by Django 3.2.19 on 2023-05-24 18:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230524_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='detail_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='large image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='small_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='small image'),
        ),
    ]
