# Generated by Django 3.2.19 on 2023-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
