# Generated by Django 3.2.19 on 2023-05-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_reservation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='player_number',
            field=models.IntegerField(null=True),
        ),
    ]
